---
- hosts: all
  become: true  # Allow Ansible to run commands with elevated privileges (sudo)

  tasks:
    - name: Install Docker and Docker Compose
      apt:
        name:
          - docker
          - docker-compose
        state: present

    - name: Create Docker group
      group:
        name: docker
        state: present

    - name: Add user to Docker group
      user:
        name: "{{ ansible_user }}"  # Current user
        groups: docker
        append: yes

    - name: Build Docker images
      docker_image:
        name: "{{ item.name }}"
        state: present
        build:
          path: "{{ item.path }}"
      loop:
        - name: frontend
          path: ./frontend
        - name: backend
          path: ./backend

    - name: Start Docker Compose services
      docker_compose:
        project_name: custom-fe-be  # Match your project name
        state: started

    - name: Create PostgreSQL database (optional)
      postgresql_db:
        name: your_database_name  # Replace with your desired database name
        owner: postgres
        state: present

    - name: Grant database access to backend user (optional)
      postgresql_user:
        name: backend_user  # Replace with your desired username
        password: your_backend_password  # Replace with your desired password
        privileges: "{{ item }}"
      loop:
        - ALL PRIVILEGES ON your_database_name  # Replace values as needed

  handlers:
    - name: Reload Docker daemon after installation
      service:
        name: docker
        state: restarted

    - name: Restart Docker Compose services on failure
      docker_compose:
        
