version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Map container port 3000 to host port 3000
    environment:
      - BACKEND_URL=http://backend:8000  # Set backend URL dynamically
    volumes:
      - ./frontend:/app  # Mount application code from host directory

  backend:
    build: ./backend
    ports:
      - "8000:8000"  # Map container port 8000 to host port 8000
    environment:
      - SECRET_KEY: ${SECRET_KEY}  # Placeholder for secret key
      - DATABASE_URL: postgres://postgres:postgres@postgres:5432/your_database_name  # Placeholder for database connection string
    volumes:
      - ./backend:/app  # Mount application code from host directory

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD: postgres  # Replace with your desired password
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persist database data

volumes:
  postgres-data:  # Named volume for persistent database storage
